services:
  kafka-spring-course:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-spring-course
    hostname: kafka  # 設置主機名，與配置中的 kafka:29092 一致
    ports:
      - 9092:9092  # 外部訪問端口
    environment:
      # ===== KRaft 模式核心配置 (移除 Zookeeper) =====
      KAFKA_NODE_ID: 1  # 節點唯一標識
      KAFKA_PROCESS_ROLES: 'broker,controller'  # 同時擔任 broker 和 controller 角色
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'  # 控制器投票配置
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'  # 控制器監聽器名稱
      
      # ===== 監聽器配置 =====
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT  # 內部 broker 間通信
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'  # 所有監聽器
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092  # 對外公布的監聽器
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'  # 安全協議映射
      
      # ===== 複製和事務配置 =====
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # offset topic 複製因子
      
      # ===== 主題管理配置 =====
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'  # 自動創建主題
      KAFKA_DELETE_TOPIC_ENABLE: 'true'  # 允許刪除主題
      
      # ===== 集群標識 =====
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'  # 集群唯一標識 (KRaft 模式必需)
